namespace PoESkillTree.Computation.Common.Builders.Skills
{
    public enum Keyword
    {
        Attack,
        Spell,
        Projectile,
        Bow,
        AreaOfEffect,
        Melee,
        Totem,
        Curse,
        Trap,
        Movement,
        Mine,
        Vaal,
        Aura,
        Golem,
        Minion,
        Warcry,
        Herald,
        Offering,
        CounterAttack,
        Physical,
        Lightning,
        Cold,
        Fire,
        Chaos,
    }
}